### ISSUE TITLE
Is the demo working properly?

### ISSUE THREAD

**Issue by bramley** [braune-digital/ckeditor-emojione#2]
Is the demo working properly? It seems to just show the unicode characters rather than images. Is that correct?
![image](https://cloud.githubusercontent.com/assets/3147688/23201998/f64015f4-f8d3-11e6-8a15-31832b7a897a.png)

**Comment by hbraune** [comment]
@bramley Could you please tell us which browser and operating system is used on your screenshot?

**Comment by bramley** [comment]
I get the same result using Firefox 51.0.1 and Chromium 55.0 on Linux Mint 18.1

**Comment by bramley** [comment]
It seems to be a known problem with Firefox on Ubuntu with fonts that show emojis.
